### ISSUE TITLE
safe_load_all() raises ConstructorError where safe_load() does not.

### ISSUE THREAD

**Issue by SimonMossmyr** [yaml/pyyaml.org#7]
# Description
`safe_load_all()` raises `yaml.constructor.ConstructorError` for tag `!include` where `safe_load()` does not.

# Steps to reproduce
1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html)
2. Create conda environment: 
```
...$ conda create -n foo python=3 PyYAML
...$ conda activate foo
```
3. Create file `foo.py`:

```python
import yaml

# This works fine
try:
    yaml.safe_load(
        """
        includes:
          - !include some_file.yaml
        """
    )
except yaml.YAMLError as e:
    pass

# This does not
try:
    docs = yaml.safe_load_all(
        """
        includes:
          - !include some_file.yaml
        """
    )
except yaml.YAMLError as e:
    pass

for doc in docs:
    pass
```
4: Run: `(foo) ...$ python foo.py`

# Error
```
Traceback (most recent call last):
  File "foo.py", line 25, in <module>
    for doc in docs:
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 37, in get_data
    return self.construct_document(self.get_node())
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 121, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 121, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/home/moss/miniconda3/envs/test/lib/python3.8/site-packages/yaml/constructor.py", line 418, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!include'
  in "<unicode string>", line 3, column 13:
              - !include some_file.yaml
                ^
```

**Comment by perlpunk** [comment]
This should rather be opened here: https://github.com/yaml/pyyaml/issues

However, I think you're mistaken. Both methods raise an exception, and they should, because the `!include` tag is nowhere defined.
But for the call of `safe_load` you're actually ignoring the exception, so you of course never see it. Not sure whe you do this.

For the call of `safe_load_all` you're also ignoring the exception, but it actually returns a generator object and only starts to parse/load the YAML when you actually iterate over it, so that's why you see the exception here.

I'm closing this because I don't see a bug.

**Comment by SimonMossmyr** [comment]
My mistake, didn't look too closely at the repo name.
